### ISSUE TITLE
不要merge master

### ISSUE THREAD

**Issue by Bankq** [localsnake/localsnake.org#12]
@qianyu @qdx 对于所有人来说，dev分支就是master分支，master分支是用来deploy的。
我看到你俩merge到了master上，下次注意，只有在我们deploy的时候，才把dev分支merge到master上并打上标签，这样子随时都可以退回到一个稳定的版本。

**Comment by qdx** [comment]
我merge到master去了？囧……我不想这么干的……回头我看看是哪里弄错了……
在 2012/10/18 11:53 AM，"Bank Qian" notifications@github.com写道：

**Comment by Bankq** [comment]
你看一下历史-----一塌糊涂。。。。。

2012/10/18 qdx notifications@github.com

> 我merge到master去了？囧……我不想这么干的……回头我看看是哪里弄错了……
> 在 2012/10/18 11:53 AM，"Bank Qian" notifications@github.com写道：
> 
> > @qianyu https://github.com/qianyu @qdx <https://github.com/qdx
> > 对于所有人来说，dev分支就是master分支，master分支是用来deploy的。
> > 
> > 我看到你俩merge到了master上，下次注意，只有在我们deploy的时候，才把dev分支merge到master上并打上标签，这样子随时都可以退回到一个稳定的版本。
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/localsnake/localsnake.org/issues/12>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/localsnake/localsnake.org/issues/12#issuecomment-9577823.

## 

Best regards,
   Hang Qian
