### ISSUE TITLE
Front page needed!

### ISSUE THREAD

**Issue by Bankq** [localsnake/localsnake.org#7]
@imposimon @qdx @qiangrw @qiany @cat810 @heloyu

恭喜大家都熟悉了开发流程并且成功建立了自己的目录（某些人除外）
现在我们需要商讨一下首页的内容。
1. 放什么内容?（团队介绍？我们是做什么的？我们的目标？我们的理想？我们是谁？）
2. 如何规划？
3. 简单网页还是复杂网页？

望在回复中探讨～

**Comment by qiangrw** [comment]
1. 团队介绍肯定是必须的，来源，团队成员介绍， 我们做过什么东西，简介，我们的活动页面
2. 几个标签页分隔各个部分
3. 界面越简洁越好

这些其实都是后话，其实我们得先做个东西出来才可以有东西写啊。

**Comment by Bankq** [comment]
Exactly.

最近有各种同学聚会，但是时间地点敲定总是很麻烦，总需要一个中心人在来回协调，我想我们能不能做这样一个供大家敲定聚会详情的应用？

2012/7/15 RunweiQiang <
reply@reply.github.com

> 1. 团队介绍肯定是必须的，来源，团队成员介绍， 我们做过什么东西，简介，我们的活动页面
> 2. 几个标签页分隔各个部分
> 3. 界面越简洁越好
> 
> 这些其实都是后话，其实我们得先做个东西出来才可以有东西写啊。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/localsnake/localsnake.org/issues/7#issuecomment-6988380

## 

Best regards,
   Hang Qian

**Comment by DylanYu** [comment]
首页简洁，类似于个人简历。

制定聚会详情的应用，有点意思。

**Comment by qdx** [comment]
好主意！我赞成！

2012/7/15 Hang Qian <
reply@reply.github.com

**Comment by qiangrw** [comment]
这个应用做出来很实用呀，大家先探讨下需求吧。大家积极修正。

# 聚会组织者
- 发布聚会讨论Ticket，制定Ticket探讨结束时间
- Ticket结束时间到时，自动生成方案（包括最优和备选方案），推送给所有成员

# 班级成员
- 察看ticket
- 添加自己方便的时间地点（或者给已经存在的时间、地点+1），默认全选说明自己哪里哪天都方便

**Comment by Bankq** [comment]
我来想个原始方案然后建个项目给大家看看哈，大概明天，今天中午同学聚会……

2012/7/15 qdx <
reply@reply.github.com

> 好主意！我赞成！
> 
> 2012/7/15 Hang Qian <
> reply@reply.github.com
> 
> > Exactly.
> > 
> > 最近有各种同学聚会，但是时间地点敲定总是很麻烦，总需要一个中心人在来回协调，我想我们能不能做这样一个供大家敲定聚会详情的应用？
> > 
> > 2012/7/15 RunweiQiang <
> > reply@reply.github.com
> > 
> > > 1. 团队介绍肯定是必须的，来源，团队成员介绍， 我们做过什么东西，简介，我们的活动页面
> > > 2. 几个标签页分隔各个部分
> > > 3. 界面越简洁越好
> > > 
> > > 这些其实都是后话，其实我们得先做个东西出来才可以有东西写啊。
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/localsnake/localsnake.org/issues/7#issuecomment-6988380
> > 
> > 
> > ## 
> > 
> > Best regards,
> >    Hang Qian
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/localsnake/localsnake.org/issues/7#issuecomment-6988395
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/localsnake/localsnake.org/issues/7#issuecomment-6988423

## 

Best regards,
   Hang Qian

**Comment by Bankq** [comment]
跟我想的惊人的相似

补充：
#参与者：
对一个时间段，有四个状态可选：“可以去；不确定，但估计可以；不确定，但估计不行；不行”
对于组织者提出的地点如果不满意，则可以自己提出新的地点，后参与的人可以看到前面所有人提出的地点并进行投票

#组织者：
对系统最后生成的方案可以做策略的选择，比如“参与人数最多的方案”，"参与人数大于X的前提下时间最近的方案”，“全员参与的方案”等等，方便不同聚会的需求。

大家有什么想法，说起来

2012/7/15 RunweiQiang <
reply@reply.github.com

> 这个应用做出来很实用呀，大家先探讨下需求吧。大家积极修正。
> 
> # 聚会组织者
> - 发布聚会讨论Ticket，制定Ticket探讨结束时间
> - Ticket结束时间到时，自动生成方案（包括最优和备选方案），推送给所有成员
> 
> # 班级成员
> - 察看ticket
> - 添加自己方便的时间地点（或者给已经存在的时间、地点+1），默认全选说明自己哪里哪天都方便
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/localsnake/localsnake.org/issues/7#issuecomment-6988431

## 

Best regards,
   Hang Qian

**Comment by imposimon** [comment]
推送的时候可以推送到
手机 邮件 Google Calendar
然后我觉得还可以搞手机客户端

**Comment by Bankq** [comment]
我就是那种信web不信app的人……
这个还是web先搞吧

On Sun, Jul 15, 2012 at 11:07 AM, Cunxin Jia <
reply@reply.github.com

> wrote:
> 
> 推送的时候可以推送到
> 手机 邮件 Google Calendar
> 然后我觉得还可以搞手机客户端
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/localsnake/localsnake.org/issues/7#issuecomment-6988650

## 

Best regards,
   Hang Qian

**Comment by DylanYu** [comment]
需求关键一点：所有人都能及时知道“需要我来投票了”，避免弃权的情况

2012/7/15 Hang Qian <
reply@reply.github.com

> 我就是那种信web不信app的人……
> 这个还是web先搞吧
> 
> On Sun, Jul 15, 2012 at 11:07 AM, Cunxin Jia <
> reply@reply.github.com
> 
> > wrote:
> > 
> > 推送的时候可以推送到
> > 手机 邮件 Google Calendar
> > 然后我觉得还可以搞手机客户端
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/localsnake/localsnake.org/issues/7#issuecomment-6988650
> 
> ## 
> 
> Best regards,
>    Hang Qian
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/localsnake/localsnake.org/issues/7#issuecomment-6988657

## 

Best regards,
Yu, Dongliang

**Comment by qiangrw** [comment]
所以说管理员可以指定班级成员的maillist，发送邮件提醒其投票。
而指定maillist，即添加用户这个功能要做得足够智能，否则是一件很麻烦的事情

**Comment by Bankq** [comment]
我能想到就是用人人网API

Best Regards,
     Hang Qian

On Jul 15, 2012, at 11:39 AM, RunweiQiang
reply@reply.github.com
wrote:

**Comment by qdx** [comment]
提供一个日历，指定日历中的某个时间段，所有人上去把时间段中自己没空的日子做个标记，系统自动找出最多人有空的日子，也可以查看在每个日子里面是谁有空谁没空。我也觉得暂时没有必要做手机的APP

2012/7/15 Hang Qian <
reply@reply.github.com

**Comment by Bankq** [comment]
好像有人做了
http://www.doodle.com/
大家看看，我们还能做点什么不一样的

2012/7/15 qdx <
reply@reply.github.com

> 提供一个日历，指定日历中的某个时间段，所有人上去把时间段中自己没空的日子做个标记，系统自动找出最多人有空的日子，也可以查看在每个日子里面是谁有空谁没空。我也觉得暂时没有必要做手机的APP
> 
> 2012/7/15 Hang Qian <
> reply@reply.github.com
> 
> > 我能想到就是用人人网API
> > 
> > Best Regards,
> >      Hang Qian
> > 
> > On Jul 15, 2012, at 11:39 AM, RunweiQiang
> > reply@reply.github.com
> > wrote:
> > 
> > > 所以说管理员可以指定班级成员的maillist，发送邮件提醒其投票。
> > > 而指定maillist，即添加用户这个功能要做得足够智能，否则是一件很麻烦的事情
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/localsnake/localsnake.org/issues/7#issuecomment-6988787
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/localsnake/localsnake.org/issues/7#issuecomment-6988793
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/localsnake/localsnake.org/issues/7#issuecomment-6991732

## 

Best regards,
   Hang Qian

**Comment by qdx** [comment]
我们能做墙内的……

**Comment by qiangrw** [comment]
有道理！ 国内有类似的吗？
没有就可以做啊。

On Tue, Jul 17, 2012 at 11:25 AM, qdx <
reply@reply.github.com

> wrote:
> 
> 我们能做墙内的……
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/localsnake/localsnake.org/issues/7#issuecomment-7025804

## 

Best Regards!
Qiang Runwei

**Comment by qdx** [comment]
我觉得会被河蟹，因为有可能非法集会

**Comment by qiangrw** [comment]
你想得太多了吧...

On Tue, Jul 17, 2012 at 11:28 AM, qdx <
reply@reply.github.com

> wrote:
> 
> 我觉得会被河蟹，因为有可能非法集会
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/localsnake/localsnake.org/issues/7#issuecomment-7025839

## 

Best Regards!
Qiang Runwei

**Comment by qdx** [comment]
要不然为嘛国内没有呢……

**Comment by Bankq** [comment]
非法集会和提供非法集会的app有区别么？
是不是要咨询一下法律人士……

On Tue, Jul 17, 2012 at 11:33 AM, qdx <
reply@reply.github.com

> wrote:
> 
> 要不然为嘛国内没有呢……
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/localsnake/localsnake.org/issues/7#issuecomment-7025897

## 

Best regards,
   Hang Qian

**Comment by qdx** [comment]
这个问题不在我们cser的讨论范围内了……我只是吐槽而已……我是觉得这个主意很不错，值得一做

**Comment by Bankq** [comment]
嗯，哪个doodle你看了么，我们能做点什么不一样的？

2012/7/17 qdx <
reply@reply.github.com

> 这个问题不在我们cser的讨论范围内了……我只是吐槽而已……我是觉得这个主意很不错，值得一做
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/localsnake/localsnake.org/issues/7#issuecomment-7026153

## 

Best regards,
   Hang Qian

**Comment by qdx** [comment]
墙内外的差别就不说了，doodle貌似木有商议地点的功能，其他我们想到的功能基本上都有了。

**Comment by qiangrw** [comment]
这个不知道晴律师知不知道啊？ @qdx

2012/7/17 Hang Qian <
reply@reply.github.com

> 非法集会和提供非法集会的app有区别么？
> 是不是要咨询一下法律人士……
> 
> On Tue, Jul 17, 2012 at 11:33 AM, qdx <
> reply@reply.github.com
> 
> > wrote:
> > 
> > 要不然为嘛国内没有呢……
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/localsnake/localsnake.org/issues/7#issuecomment-7025897
> 
> ## 
> 
> Best regards,
>    Hang Qian
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/localsnake/localsnake.org/issues/7#issuecomment-7026127

## 

Best Regards!
Qiang Runwei

**Comment by qdx** [comment]
你可以去请教请教~~嘿嘿嘿

**Comment by DylanYu** [comment]
缺少一开始的建议时间地点功能，doodle只由管理员指定。
另外对于墙内用户而言，电子邮件联系会显得很不可靠，如果不是我们几个人用的话。

**Comment by qiangrw** [comment]
在国内利用校内和微薄接口，像已定的分组发送request会更加方便，也更适合中国国情。
谁最近有时间写个详细需求分析？
